import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import { axiosInstance } from "./api";
import { Root } from "@/typescript/common.all.interface";
import { endpoints } from "./api/endpoints.config";
import Table from '@mui/material/Table';
import TableBody from '@mui/material/TableBody';
import TableCell from '@mui/material/TableCell';
import TableContainer from '@mui/material/TableContainer';
import TableHead from '@mui/material/TableHead';
import TableRow from '@mui/material/TableRow';
import Paper from '@mui/material/Paper';
import { Box, Button, Container, Popover, Typography } from "@mui/material";
import { useState } from "react";
import Link from "next/link";

export default function Home() {
  const { isPending, error, data } = useQuery({
    queryKey: ['assets'],
    queryFn: async () => {
      const dta = await axiosInstance.get<Root>(
        endpoints.fetchData.assets
      )
      // console.log('assets', dta);
      return dta?.data?.data

    }
  })
  console.log('assets', data)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {
          isPending ? (
            <>
              <h1>Loading ...</h1>
            </>
          ) : (
            <>
              <Container>
                <TableContainer component={Paper}>
                  <Table sx={{ minWidth: 650 }} aria-label="simple table">
                    <TableHead sx={{backgroundColor: '#262927'}}>
                      <TableRow>
                        <TableCell sx={{ fontWeight: 'bold', color: 'white' }}>Id</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Rank</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Symbol</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Name</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Supply</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Max Supply</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Market CapUsd</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Volume Usd24Hr</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Price Usd</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold', color: 'white' }}>Change Percent 24Hr</TableCell>
                        <TableCell align="right" sx={{ fontWeight: 'bold' }}>Vwap24hr</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {data?.map((item, key) => (
                        <TableRow
                          key={key}
                          sx={{ '&:last-child td, &:last-child th': { border: 0 }, textDecoration: 'none' }}
                          component={Link}
                          href={`/${item?.id}`}
                          hover
                        >
                          <TableCell component="th" scope="row">
                              {item?.id}
                          </TableCell>
                          <TableCell align="right">{item?.rank}</TableCell>
                          <TableCell align="right">{item?.symbol}</TableCell>
                          <TableCell align="right">{item?.name}</TableCell>
                          <TableCell align="right">{item?.supply}</TableCell>
                          <TableCell align="right">{item?.maxSupply}</TableCell>
                          <TableCell align="right">{item?.marketCapUsd}</TableCell>
                          <TableCell align="right">{item?.volumeUsd24Hr}</TableCell>
                          <TableCell align="right">{item?.priceUsd}</TableCell>
                          <TableCell align="right">{item?.changePercent24Hr}</TableCell>
                          <TableCell align="right">{item?.vwap24Hr}</TableCell>
                        </TableRow>
                      ))}
                    </TableBody>
                  </Table>
                </TableContainer>
              </Container>
            </>
          )
        }
      </main>
    </>
  );
}
